name: Audits

on:
  pull_request:
  push:
    branches: main

permissions:
  contents: read

jobs:
  cargo-vet:
    name: Vet Rust dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # v1.0.0
        id: toolchain
      - run: rustup override set ${{steps.toolchain.outputs.name}}
      - run: cargo install cargo-vet --version ~0.9
      - run: cargo vet --locked

  cargo-deny:
    name: Check licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: EmbarkStudios/cargo-deny-action@34899fc7ba81ca6268d5947a7a16b4649013fea1 # v2.0.11
        with:
          command: check licenses
