name: librustzcash documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: prepare
        uses: ./.github/actions/prepare
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # v1.0.0
        id: toolchain
        with:
          toolchain: stable
      - run: rustup override set ${{steps.toolchain.outputs.name}}

      - name: Build latest rustdocs
        run: >
          cargo doc
          --no-deps
          --workspace
          ${{ steps.prepare.outputs.feature-flags }}
        env:
          RUSTDOCFLAGS: -Z unstable-options --enable-index-page --cfg docsrs

      - name: Move latest rustdocs into book
        run: |
          mkdir -p ./book/book/rustdoc
          mv ./target/doc ./book/book/rustdoc/latest

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
